### ISSUE TITLE
Suggestion for merging old website and new website.

### ISSUE THREAD

**Issue by spicata** [EddieTheEd/obsidiannotes-v.2#1]
# Suggestion for merging old website and new website.

You should make your old website redirect to your new website. You can do this by adding the following to the `<head>` tag of your old website.

```
<meta http-equiv="refresh" content="0; url='https://eddietheed.github.io/obsidiannotes-v.2/'" />
```

This should redirect your old website to your new website.

**Comment by EddieTheEd** [comment]
no
