### ISSUE TITLE
My heart 

### ISSUE THREAD

**Issue by EddieTheEd** [EddieTheEd/obsidiannotes-v.2#4]
It yearns for Christian choe

❤️‍🔥❤️‍🔥❤️‍🔥❤️‍🔥

**Comment by spicata** [comment]
> "Heartaches, heartaches
> My loving you, they're only heartaches
> Your kiss was such a sacred thing to me
> I can't believe it's just a burning memory
> Heartaches, heartaches
> What does it matter how my heart breaks?
> I should be happy with someone new
> But my heart aches for you"
> \- Some guy

🫀

**Comment by spicata** [comment]
> Does not solve the issue of my heart yearning

Very sorry. I will formulate ways of solving this issue (issue?).

P.S. Heart I gave you: 💙
Heart you gave me: 💗

**Comment by spicata** [comment]
Have a read through [this](https://jzhao.xyz/thoughts/tribe-flourishing).

P.S. This is what happens when you don't you Discord

**Comment by EddieTheEd** [comment]
No more jzhao

We both think the guy is great, but you're going a little over the top

**Comment by spicata** [comment]
Jacky Zhao is a very cool guy.

Also, I've gone insane. (This is what happens if you make 22 notes simply about habits)
